### PR TITLE
[ISSUE #767]🔥Refactor all error handling🚀

### LINKED ISSUE #767: [Enhancement⚡️] Refactor all error handling
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

_No response_

### Motivation

_No response_

### Describe the Solution You'd Like

_No response_

### Describe Alternatives You've Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mxsm**
### Which Issue(s) This PR Fixes(Closes)

Fixes #767 

## Summary by CodeRabbit

- **Refactor**
  - Unified error handling across the project by renaming various error types to a general `Error`.
  - Simplified method signatures and return types for consistency and clarity.

- **Chores**
  - Updated logging from `log::info` to `tracing::info` for better tracing capabilities.
  - Added `tracing` dependency alongside `tokio`.

- **New Features**
  - Introduced platform-specific signal handling for Unix and Windows, including a new function `wait_for_signal()` to handle SIGINT and SIGTERM signals using tokio.

### CODE REVIEW

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Review by SpaceXCN — APPROVED** [review]

**Pull request merged**
