### PR TITLE
[ISSUE #545]🔧Update label-on-approval.yml

### LINKED ISSUE #545: [Enhancement] Update label-on-approval.yml
### Before Creating the Enhancement Request

- [ ] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

_No response_

### Motivation

_No response_

### Describe the Solution You'd Like

_No response_

### Describe Alternatives You've Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mxsm**
### Which Issue(s) This PR Fixes(Closes)

Fixes #545 

## Summary by CodeRabbit

- **Chore**
  - Renamed workflow from "Label on Approval" to "Add Label on Approval".
  - Updated job and step names within the workflow for clarity.
  - Enhanced the logic to check for approval from specific collaborators.
  - Added a new step to label pull requests if approved by specified collaborators.
  - Updated versions for `actions/checkout` and `actions/github-script` for better performance and security.

### CODE REVIEW

**Review by TeslaRustor — APPROVED** [review]

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Review by TeslaRustor — APPROVED** [review]

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Review by TeslaRustor — APPROVED** [review]

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Review by TeslaRustor — APPROVED** [review]

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Review by TeslaRustor — APPROVED** [review]

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Review by TeslaRustor — APPROVED** [review]

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Review by TeslaRustor — APPROVED** [review]

**Review by TeslaRustor — APPROVED** [review]

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Pull request merged**
