### PR TITLE
[ISSUE #1089]🔥Optimize api according to rust api-guidelines🎨

### LINKED ISSUE #1089: [Enhancement⚡️] Optimize api according to rust api-guidelines
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

_No response_

### Motivation

_No response_

### Describe the Solution You'd Like

_No response_

### Describe Alternatives You've Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mxsm**
### Which Issue(s) This PR Fixes(Closes)

Fixes #1089

## Release Notes

- **New Features**
	- Streamlined response body handling across various request and response methods in both the broker and client components, enhancing readability and maintainability.

- **Bug Fixes**
	- Improved error handling for body encoding in RPC requests to prevent setting invalid values.

- **Documentation**
	- Updated method signatures for clarity regarding body handling, eliminating unnecessary option wrapping.

These changes aim to enhance the overall performance and reliability of the messaging system.

### CODE REVIEW

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Review by SpaceXCN — APPROVED** [review]

**Review by TeslaRustor — APPROVED** [review]

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Review by TeslaRustor — APPROVED** [review]

**Review by SpaceXCN — APPROVED** [review]

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Review by TeslaRustor — APPROVED** [review]

**Review by TeslaRustor — APPROVED** [review]

**Pull request merged**
