### PR TITLE
[ISSUE #1173]🔥Optimize use CheetahString replace Std String🎨

### LINKED ISSUE #1173: [Enhancement⚡️] Optimize use CheetahString replace Std String
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

_No response_

### Motivation

_No response_

### Describe the Solution You'd Like

_No response_

### Describe Alternatives You've Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mxsm**
### Which Issue(s) This PR Fixes(Closes)

Fixes #1173 

## Release Notes

- **New Features**
  - Transitioned from standard string types to `CheetahString` across various components for improved performance and type safety.
  - Enhanced handling of string data in methods related to topics, brokers, and connections.

- **Bug Fixes**
  - Updated parameter and return types in multiple methods to ensure compatibility with `CheetahString`.

- **Documentation**
  - Improved method signatures and internal logic for better clarity and consistency in handling string types.

- **Refactor**
  - Streamlined code by removing unnecessary conversions and adopting `CheetahString` throughout the codebase.

These changes enhance the overall functionality and performance of the system, particularly in string handling and data management.

### CODE REVIEW

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Review by TeslaRustor — APPROVED** [review]

**Pull request merged**
