### PR TITLE
[ISSUE #834]Support AdminBrokerProcessor get_system_topic_list_from_broker

### LINKED ISSUE #834: [Feature🚀] Support AdminBrokerProcessor get_system_topic_list_from_broker
### Is Your Feature Request Related to a Problem?

_No response_

### Describe the Solution You'd Like

_No response_

### Describe Alternatives You've Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by 847850277**
### Which Issue(s) This PR Fixes(Closes)

Fix #834

### Brief Description

Support AdminBrokerProcessor get_system_topic_list_from_broker

## Summary by CodeRabbit

- **New Features**
	- Introduced a method to retrieve the system topic list from the broker, enhancing administrative capabilities.
	- Added functionality to process specific requests related to system topics.
  
- **Bug Fixes**
	- No reported bugs were addressed in this release.

- **Documentation**
	- No updates to documentation were made with this release.

### CODE REVIEW

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit(AI) will review your code first🔥

**Review by SpaceXCN — APPROVED** [review]

**Pull request merged**
