### PR TITLE
Update Cargo.toml

### PR DESCRIPTION
**Pull request by flydream-ylgw**
### Which Issue(s) This PR Fixes(Closes)

Fixes #issue_id

## Summary by CodeRabbit

- **Style**
  - Improved the formatting of the dependencies in the config file for consistency.

### CODE REVIEW

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit will review your code first🔥

**Review by mxsm — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Review by SpaceXCN — APPROVED** [review]

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit will review your code first🔥

**Review by mxsm — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit will review your code first🔥

**Review by mxsm — APPROVED** [review]

**Comment by mxsm** [comment]
🚀Thanks for your contribution🎉. CodeRabbit will review your code first🔥

**Review by mxsm — APPROVED** [review]

**Pull request merged**
