### PR TITLE
[ISSUE #541]🔨Add Auto-Merge

### LINKED ISSUE #541: [Feature] Add  Auto-Merge
### Is Your Feature Request Related to a Problem?

_No response_

### Describe the Solution You'd Like

_No response_

### Describe Alternatives You've Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mxsm**
### Which Issue(s) This PR Fixes(Closes)

Fixes #541 

## Summary by CodeRabbit

- **New Features**
  - Introduced automated merging of pull requests using GitHub Actions.
  - Added automatic commenting on pull requests upon successful merge.

### CODE REVIEW

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Comment by mxsm** [comment]
🚀This PR has been automatically merged with squash.🚀

**Comment by mxsm** [comment]
🚀This PR has been automatically merged with squash.🚀

**Review by TeslaRustor — APPROVED** [review]

**Pull request merged**
