### PR TITLE
[ISSUE #542]🔨Add auto add label for pr approval

### LINKED ISSUE #542: [Feature] Add auto add label for pr
### Is Your Feature Request Related to a Problem?

_No response_

### Describe the Solution You'd Like

_No response_

### Describe Alternatives You've Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mxsm**
### Which Issue(s) This PR Fixes(Closes)

Fixes #542 

## Summary by CodeRabbit

- **New Features**
  - Introduced a workflow that automatically labels pull requests as "approved" and "auto merge" when a repository collaborator with admin permissions approves the PR.

### CODE REVIEW

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Review by shadowsoy — APPROVED** [review]

**Review by TeslaRustor — APPROVED** [review]

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Comment by mxsm** [comment]
@coderabbitai review Please review this PR.

**Pull request merged**
